config/routes.rb
StaticBlocks::Engine.routes.draw do
  scope ":locale", locale: /#{StaticBlocks.config.locales.join("|")}/ do
    resources :snippets do
      collection do
        get 'export'
        get 'export_translations'
        post :import
        post :import_translations
      end
    end
    root to: 'snippets#index'
  end
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  match '', to: redirect("/static_blocks/#{I18n.default_locale}/snippets")
end

app/models/static_blocks/snippet.rb
module StaticBlocks
  class Snippet < ActiveRecord::Base
    attr_accessible :content, :status, :title
    after_save :clear_cache
    scope :published, where(:status => 'published')
    translates :content
    validates :title, uniqueness: true

    def to_s
      content
    end

    def clear_cache
      Rails.cache.delete("snippet::"+I18n.locale.to_s+"::"+title)
    end

    def self.to_csv(options = {})
      snippets = self.connection.select_all('select * from static_blocks_snippets')
      snippets_column_names = snippets.first.keys
      CSV.generate(options) do |csv|
        csv << snippets_column_names
        snippets.each do |s|
          csv << s.values_at(*snippets_column_names)
        end
      end
    end

    def self.translations_to_csv(options = {})
      translations = self.connection.select_all('
        SELECT s.title, t.* FROM static_blocks_snippet_translations t
        INNER JOIN static_blocks_snippets s
        ON t.static_blocks_snippet_id = s.id
        ')
      if translations.empty?
        flash[:error] = "There are no translations"
        return
      end
      translation_column_names = translations.first.keys
      CSV.generate(options) do |csv|
        csv << translation_column_names
        translations.each do |t|
          csv << t.values_at(*translation_column_names)
        end
      end
    end

    def self.import(file)
      CSV.foreach(file.path, headers: true) do |row|
        snippet = find_by_title(row["title"]) || new
        snippet.attributes = row.to_hash.slice(*accessible_attributes)
        snippet.save!
      end
    end

    def self.import_translations(file)
      # delete all translations
      delete_sql = "DELETE FROM static_blocks_snippet_translations"
      translation = ActiveRecord::Base.connection.execute(delete_sql)

      # add all translations
      CSV.foreach(file.path, headers: true) do |row|
        static_block = find_by_title(row['title'])

        # return if nil
        # we don't want to update or insert a translation if the snippet doesn't exist
        return if static_block.nil?

        # create new translation
        sql_array = ["
        INSERT INTO static_blocks_snippet_translations
        (static_blocks_snippet_id, locale, content, created_at, updated_at) VALUES
        (?, ?, ?, ?, ?)", static_block.id, row['locale'], row['content'], row['created_at'], row['updated_at']]
        insert_sql = sanitize_sql_array(sql_array)

        ActiveRecord::Base.connection.execute(insert_sql)

        # manually clear the cache for that snippet
        Rails.cache.delete("snippet::#{row['locale']}::#{row['title']}")
      end
    end
  end
end

app/controllers/static_blocks/application_controller.rb
module StaticBlocks
  class ApplicationController < ActionController::Base

    if StaticBlocks.config.http_auth
      http_basic_authenticate_with :name => StaticBlocks.config.username, :password => StaticBlocks.config.password
    end

    before_filter :set_locale

    private

    def set_locale
      I18n.locale = params[:locale] if params[:locale].present?
    end

    def default_url_options(options = {})
      {locale: I18n.locale}
    end
  end
end

app/controllers/static_blocks/snippets_controller.rb
require_dependency "static_blocks/application_controller"

module StaticBlocks
  class SnippetsController < ApplicationController

    def export
      unless Snippet.any?
        flash[:error] = "There are no snippets"
        redirect_to root_url
        return
      end

      t = Time.now.strftime('%Y-%m-%d-%H-%M-%S')
      app_name = Rails.application.class.parent_name
      filename = "#{app_name}-snippets-#{t}.csv"

      respond_to do |format|
        format.csv do
          send_data Snippet.to_csv, :filename => filename
        end
      end
    end

    def export_translations
      unless Snippet.any?
        flash[:error] = "There are no translations"
        redirect_to root_url
        return
      end

      t = Time.now.strftime('%Y-%m-%d-%H-%M-%S')
      app_name = Rails.application.class.parent_name
      filename = "#{app_name}-translations-#{t}.csv"

      respond_to do |format|
        format.csv do
          send_data Snippet.translations_to_csv, :filename => filename
        end
      end
    end

    def import
      if params[:file].nil?
        redirect_to root_url
        flash[:error] = "You did not attach a file."
      elsif params[:file].original_filename.include? '-snippets'
        Snippet.import(params[:file])
        redirect_to root_url, notice: "Snippets imported"
      else
        redirect_to root_url
        flash[:error] = "Error. Please upload a valid snippets csv."
      end
    end

    def import_translations
      if params[:file].nil?
        redirect_to root_url
        flash[:error] = "You did not attach a file."
      elsif params[:file].original_filename.include? '-translations'
        Snippet.import_translations(params[:file])
        redirect_to root_url, notice: "Snippet translations imported"
      else
        redirect_to root_url
        flash[:error] = "Error. Please upload a valid static-blocks-translations csv."
      end
    end

    # GET /static_blocks
    # GET /static_blocks.json
    def index
      @search = Snippet.order('title asc').search(params[:q])
      @snippets = @search.result(distinct: true).per_page_kaminari(params[:page]).per(10)

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @snippets }
      end
    end

    # GET /snippets/1
    # GET /snippets/1.json
    def show
      @snippet = Snippet.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @snippet }
      end
    end

    # GET /snippets/new
    # GET /snippets/new.json
    def new
      @snippet = Snippet.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @snippet }
      end
    end

    # GET /snippets/1/edit
    def edit
      @snippet = Snippet.find(params[:id])
    end

    # POST /snippets
    # POST /snippets.json
    def create
      @snippet = Snippet.new(params[:snippet])

      respond_to do |format|
        if @snippet.save
          format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
          format.json { render json: @snippet, status: :created, location: @snippet }
        else
          format.html { render action: "new" }
          format.json { render json: @snippet.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /snippets/1
    # PUT /snippets/1.json
    def update
      @snippet = Snippet.find(params[:id])

      respond_to do |format|
        if @snippet.update_attributes(params[:snippet])
          format.html { redirect_to @snippet, notice: 'Static block was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @snippet.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /snippets/1
    # DELETE /snippets/1.json
    def destroy
      @snippet = Snippet.find(params[:id])
      @snippet.destroy

      respond_to do |format|
        format.html { redirect_to snippets_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/static_blocks/static_blocks_controller.rb
require_dependency "static_blocks/application_controller"

module StaticBlocks
  class StaticBlocksController < ApplicationController

    def export
      t = Time.now.strftime('%Y%m%d%H%M%S')
      filename = "static-blocks-#{t}.csv"
      respond_to do |format|
        format.csv do
          send_data StaticBlock.to_csv, :filename => filename
        end
      end
    end

    def export_translations
      t = Time.now.strftime('%Y%m%d%H%M%S')
      filename = "static-blocks-translations-#{t}.csv"
      respond_to do |format|
        format.csv do
          send_data StaticBlock.translations_to_csv, :filename => filename
        end
      end
    end

    def import
      if params[:file].nil?
        redirect_to root_url
        flash[:error] = "You did not attach a file."
      elsif params[:file].original_filename.include? 'translations'
        redirect_to root_url
        flash[:error] = "Wrong file. You uploaded the translations."
      else
        StaticBlock.import(params[:file])
        redirect_to root_url, notice: "Static Blocks imported"
      end
    end

    def import_translations
      if params[:file].nil?
        redirect_to root_url
        flash[:error] = "You did not attach a file."
      elsif params[:file].original_filename.include? 'translations'
        StaticBlock.import_translations(params[:file])
        redirect_to root_url, notice: "Static Block translations imported"
      else
        redirect_to root_url
        flash[:error] = "Wrong file. You uploaded the default static blocks."
      end
    end

    # GET /static_blocks
    # GET /static_blocks.json
    def index
      @search = StaticBlock.order('title asc').search(params[:q])
      @static_blocks = @search.result.per_page_kaminari(params[:page]).per(10)

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @static_blocks }
      end
    end

    # GET /static_blocks/1
    # GET /static_blocks/1.json
    def show
      @static_block = StaticBlock.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @static_block }
      end
    end

    # GET /static_blocks/new
    # GET /static_blocks/new.json
    def new
      @static_block = StaticBlock.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @static_block }
      end
    end

    # GET /static_blocks/1/edit
    def edit
      @static_block = StaticBlock.find(params[:id])
    end

    # POST /static_blocks
    # POST /static_blocks.json
    def create
      @static_block = StaticBlock.new(params[:static_block])

      respond_to do |format|
        if @static_block.save
          format.html { redirect_to @static_block, notice: 'Static block was successfully created.' }
          format.json { render json: @static_block, status: :created, location: @static_block }
        else
          format.html { render action: "new" }
          format.json { render json: @static_block.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /static_blocks/1
    # PUT /static_blocks/1.json
    def update
      @static_block = StaticBlock.find(params[:id])

      respond_to do |format|
        if @static_block.update_attributes(params[:static_block])
          format.html { redirect_to @static_block, notice: 'Static block was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @static_block.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /static_blocks/1
    # DELETE /static_blocks/1.json
    def destroy
      @static_block = StaticBlock.find(params[:id])
      @static_block.destroy

      respond_to do |format|
        format.html { redirect_to static_blocks_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/static_blocks/application_helper.rb
module StaticBlocks
  module ApplicationHelper
  end
end

app/helpers/static_blocks/snippets_helper.rb
module StaticBlocks
  module StaticBlocksHelper
  end
end

app/helpers/static_blocks/static_blocks_helper.rb
module StaticBlocks
  module StaticBlocksHelper
  end
end

app/views/static_blocks/snippets/_form.html.erb
<%= form_for(@snippet) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, :class => 'wysihtml5' %>
  </div>
  <div class="field">
    <%= f.label :status %>
    <%= f.select(:status, [['Published', 'published'], ['Draft', 'draft']]) %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/static_blocks/snippets/_search.html.erb
<% if StaticBlocks.config.globalize %>

  <%= search_form_for @search do |f| %>
    <div class="field">
      <%= f.label :title_cont, "Title contains" %>
      <%= f.text_field :title_cont %>
    </div>
    <div class="field">
      <%= f.label :translations_content_cont, "Content contains" %>
      <%= f.text_field :translations_content_cont %>
    </div>
    <div class="field">
      <%= f.label :status_cont, "Status contains" %>
      <%= f.select(:status_cont, [['', ''], ['Draft', 'draft'], ['Published', 'published']]) %>
    </div>
    <div class="actions"><%= f.submit "Search" %></div>
  <% end %>

<% else %>

  <%= search_form_for @search do |f| %>
    <div class="field">
    <%= f.label :title_cont, "Title contains" %>
      <%= f.text_field :title_cont %>
    </div>
    <div class="field">
      <%= f.label :content_cont, "Content contains" %>
      <%= f.text_field :content_cont %>
    </div>
    <div class="field">
      <%= f.label :status_cont, "Status contains" %>
      <%= f.select(:status_cont, [['', ''], ['Draft', 'draft'], ['Published', 'published']]) %>
    </div>
    <div class="actions"><%= f.submit "Search" %></div>
  <% end %>

<% end %>

app/views/static_blocks/snippets/edit.html.erb
<h1>Editing snippet</h1>

<%= render 'form' %>

app/views/static_blocks/snippets/index.html.erb
<h1>Listing snippets</h1>
<div class="row">
<div class="span6">
  <h2>Search</h2>
  <%= search_form_for @search do |f| %>
    <div class="field">
      <%= f.label :title_cont, "Title contains" %>
      <%= f.text_field :title_cont %>
    </div>
    <div class="field">
      <%= f.label :translations_content_cont, "Content contains" %>
      <%= f.text_field :translations_content_cont %>
    </div>
    <div class="field">
      <%= f.label :status_cont, "Status contains" %>
      <%= f.select(:status_cont, [['', ''], ['Draft', 'draft'], ['Published', 'published']]) %>
    </div>
    <div class="actions"><%= f.submit "Search" %></div>
  <% end %>
</div>
<div class="span6">
  <h2>Import snippets</h2>
  <%= form_tag import_snippets_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import snippets" %>
  <% end %>
  <h2>Import translations</h2>
  <%= form_tag import_translations_snippets_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import translations" %>
  <% end %>
  <p class="help-block">*If you are using translations, you must import snippets first and then translations.</p>
</div>
</div>

<%= paginate @snippets, :theme => 'twitter-bootstrap' %>

<table id="static-block-list" class="table table-striped">
  <tr>
    <th style="min-width: 60px;"><%= sort_link(@search, :title, "Title") %></th>
    <th><%= sort_link(@search, :content, "Content") %></th>
    <th style="min-width: 80px;"><%= sort_link(@search, :status, "Status") %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @snippets.each do |snippet| %>
  <tr>
    <td><%= snippet.title %></td>
    <td><%= snippet.content %></td>
    <td><%= snippet.status %></td>
    <td><%= link_to 'Show', snippet_path(snippet), class: "btn btn-mini btn-success" %></td>
    <td><%= link_to 'Edit', edit_snippet_path(snippet), class: "btn btn-mini btn-warning" %></td>
    <td><%= link_to 'Destroy', snippet, class: "btn btn-mini btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>

<%= paginate @snippets, :theme => 'twitter-bootstrap' %>

app/views/static_blocks/snippets/new.html.erb
<h1>New snippet</h1>

<%= render 'form' %>

app/views/static_blocks/snippets/show.html.erb
<h1 class="pull-left">Showing Snippet</h1>

<%= link_to 'Edit', edit_snippet_path(@snippet), class: "btn btn-primary btn-warning pull-right showing-edit-button" %>

<table class="table table-striped table-bordered">
  <tr>
    <th>Title</th>
    <th>Status</th>
  </tr>
  <tr>
    <td><%= @snippet.title %></td>
    <td width="20%"><%= @snippet.status %></td>
  </tr>
</table>

<div class="well">
  <%= raw(@snippet.content) %>
</div>